### ISSUE TITLE
Das Projekt scheint ziemlich unnötig.

### ISSUE THREAD

**Issue by Crypti-x** [open-code-community/VidMe4J#1]
Ich sehe keinen Sinn in einem solchen Projekt ohne Dokumentation oder minimale Erklärung, das macht das Projekt wertlos, egal wie gut der Code ist.

**Comment by RLEXBuilding** [comment]
Wir haben, das Projekt erst gestern gestartet und da immer mehr Leute Vid.Me verwenden und es noch keine VidMe Java Library gibt. Machen wir sie, und ja Dokumentation kommt noch.

**Comment by Skyleiger** [comment]
Ich behaupte hier mal genau das Gegenteil: Gerade weil VidMe immer beliebter wird und es noch keine Java API für VidMe gibt, sehe ich einen Sinn darin, eine VidMe Java API zu coden.
Sollte dies aber dich nicht ansprechen, so kannst du auch gerne an einem anderem Projekt arbeiten. Niemand wird hier zu etwas gezwungen.
