### ISSUE TITLE
VidMe API nicht voll funktionstüchtig

### ISSUE THREAD

**Issue by Skyleiger** [open-code-community/VidMe4J#4]
Guten Abend,
Nach verschiedenen Tests habe ich beschlossen, das Projekt für mich aufzugeben.
Die VidMe API ist nicht voll funktionstüchtig und teilweise schlecht dokumentiert.
Mit diesen Vorraussetzungen kann ich nicht korrekt arbeiten.

Mit freundlichen Grüßen,
Skyleiger

**Comment by RLEXBuilding** [comment]
Da gebe ich dir recht, ich kann damit auch nicht wirklich arbeiten deswegen hab ich in die README.MD schon geschrieben, das die API nicht fertiggestellt ist.
